yarnPath: .yarn/releases/yarn-3.3.1.cjs
packageExtensions:
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/schematics": "*"
      "@angular-devkit/core": "*"
  "@angular-eslint/builder@*":
    dependencies:
      "@angular-devkit/architect": "*"