packageExtensions:
  "@angular-eslint/builder@*":
    dependencies:
      "@angular-devkit/architect": "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
