compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@angular-eslint/builder@*":
    dependencies:
      "@angular-devkit/architect": "*"
  "@angular-eslint/eslint-plugin-template@*":
    dependencies:
      "@typescript-eslint/types": "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/core": "*"
      "@angular-devkit/schematics": "*"
  "@nx/devkit@*":
    dependencies:
      "@angular-devkit/architect": "*"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
